apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: nginx-example-schedule-01
  namespace: velero
spec:
  schedule: '@every 5m30s'
  template:
    csiSnapshotTimeout: 10m
    hooks: {}
    includedNamespaces:
    - nginx-example
    storageLocation: default
    ttl: 0s
  useOwnerReferencesInBackup: false