apiVersion: velero.io/v1
kind: Backup
metadata:
  name: nginx-example-backup-0q
  namespace: velero
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: true
  includedNamespaces:
  - nginx-example
  storageLocation: default
  ttl: 720h0m0s