---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-backup-webhook-role
rules:
- apiGroups: ["velero.io"]
  resources: ["backups", "schedules"]
  verbs: ["create", "delete", "get"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-backup-webhook-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-backup-webhook-binding
subjects:
- kind: ServiceAccount
  name: velero-backup-webhook-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: velero-backup-webhook-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-backup-webhook
  namespace: default
  labels:
    app: velero-backup-webhook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: velero-backup-webhook
  template:
    metadata:
      labels:
        app: velero-backup-webhook
    spec:
      serviceAccountName: velero-backup-webhook-sa
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: velero-backup-webhook
        image: nggocnn/velero-backup-webhook:latest
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 443
          protocol: TCP
        env:
          - name: VELERO_NAMESPACE
            value: "velero"
          - name: CRON_EXPRESSION
            value: "@every 10m"
          - name: CSI_SNAPSHOT_TIMEOUT
            value: "10m"
          - name: STORAGE_LOCATION
            value: "default"
          - name: BACKUP_TTL
            value: "720h"
          - name: DEFAULT_VOLUMES_TO_FS_BACKUP
            value: "true"
          - name: BACKUP_SUFFIX
            value: "backup"
          - name: LOG_FORMAT
            value: "text"
          - name: LOG_LEVEL
            value: ""
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add: ["NET_BIND_SERVICE"]
            drop: ["ALL"]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
        livenessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: webhook-cert
          mountPath: /etc/admission-webhook/tls
          readOnly: true
      volumes:
      - name: webhook-cert
        secret:
          secretName: velero-backup-webhook-cert
---
apiVersion: v1
kind: Service
metadata:
  name: velero-backup-webhook-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: velero-backup-webhook

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: velero-backup-webhook-config
  annotations:
    cert-manager.io/inject-ca-from: default/velero-backup-webhook-server
webhooks:
- name: velero-backup-webhook.webhook.velero.io
  clientConfig:
    service:
      name: velero-backup-webhook-service
      namespace: default
      path: "/validate"
      port: 443
  rules:
  - operations: ["CREATE", "UPDATE", "DELETE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["namespaces"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
  matchPolicy: Equivalent
  timeoutSeconds: 10
